### ISSUE TITLE
Cannot create a standard instance from a spot machine image because serde skips serializing instance_termination_action

### ISSUE THREAD

**Issue by Nereuxofficial** [abdolence/gcloud-sdk-rs#141]
This is probably more of a bug in the openapi specification.

I have a machine image created from a spot instance. The plan is to create a standard instance using that image. This is possible in the browser. 

This is the code that should do this(the full code is [here](https://github.com/Nereuxofficial/gcp-live-migration)):
```rs
let instance = compute_instances_insert(
        &compute_v1_config,
        ComputePeriodInstancesPeriodInsertParams {
            project: project.clone(),
            zone,
            source_machine_image: Some(format!(
                "projects/{}/global/machineImages/{}",
                project,
                machine_image.name.as_ref().unwrap()
            )),
            instance: Some(Instance {
                name: Some(format!("nested-qemu-{}", rng.gen::<u32>())),
                scheduling: Some(Box::new(Scheduling {
                    preemptible: Some(false),
                    provisioning_model: Some(ProvisioningModel::Standard),
                    instance_termination_action: None,
                    ..Default::default()
                })),
                ..Default::default()
            }),
            ..Default::default()
        },
    )
    .await
    .unwrap();
```
When creating the instance i get this error:
```
ResponseError(ResponseContent { status: 400, content: "{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Invalid value for field 'resource.scheduling.instanceTerminationAction': 'STOP'. You cannot specify a termination action for a VM instance that has the standard provisioning model (default). To use instance termination action, the VM instance must use the Spot provisioning model.\",\n    \"errors\": [\n      {\n        \"message\": \"Invalid value for field 'resource.scheduling.instanceTerminationAction': 'STOP'. You cannot specify a termination action for a VM instance that has the standard provisioning model (default). To use instance termination action, the VM instance must use the Spot provisioning model.\",\n        \"domain\": \"global\",\n        \"reason\": \"invalid\"\n      }\n    ]\n  }\n}\n", entity: Some(UnknownValue(Object {"error": Object {"code": Number(400), "errors": Array [Object {"domain": String("global"), "message": String("Invalid value for field 'resource.scheduling.instanceTerminationAction': 'STOP'. You cannot specify a termination action for a VM instance that has the standard provisioning model (default). To use instance termination action, the VM instance must use the Spot provisioning model."), "reason": String("invalid")}], "message": String("Invalid value for field 'resource.scheduling.instanceTerminationAction': 'STOP'. You cannot specify a termination action for a VM instance that has the standard provisioning model (default). To use instance termination action, the VM instance must use the Spot provisioning model.")}})) })
```
This is despite explicitly setting the instance_termination_action to be None(i know this is the default value).

My guess as to why this is:
- Serde skips serializing the value when it is None, which is correct in the normal case
- GCP inherits the field from the created image, where it is set to STOP

This is seemingly confirmed by deleting the ` skip_serializing_if = "Option::is_none"` part of the macro above the field and running cargo clean and cargo run, upon which the instance is successfully created.

**Comment by abdolence** [comment]
Hm, interesting. Let me check if I can do something here. You're right, it is some kind of limitation coming from Open API spec generator. For convenience for most of the APIs `None` means absence of fields, here we want to actually have explicit nulls. Need to figure out if there is better way to handle this.

**Comment by abdolence** [comment]
This particular field can be fixed this way:
https://github.com/abdolence/gcloud-sdk-rs/pull/143

Let me know what do you think.
I would appreciate help with the testing, since you're already using this API in your application.
Also let me know if I need to mark other fields there the same way. 

This is not ideal, fixing the original spec, but better than having a bug inside.
