### ISSUE TITLE
Relax `Sync` requirement for `storage_objects_insert_ext_stream`

### ISSUE THREAD

**Issue by zackangelo** [abdolence/gcloud-sdk-rs#146]
The `storage_objects_insert_ext_stream` extension method for uploading a stream to GCS requires that the `Stream` is `Sync`. But there doesn't appear to be a need for it and prevents being able to easily proxy an incoming `Body` stream from axum (which is not `Sync`). 

https://github.com/abdolence/gcloud-sdk-rs/blob/7a447c159fbd1fcad15375ecdadf39fea1a89850/gcloud-sdk/src/rest_apis/google_rest_apis/storage_v1/apis/objects_api.rs#L2382-L2399

I can open a PR if we're okay with this change.

**Comment by abdolence** [comment]
Right, thanks for reporting. It is an easy fix, I'll handle it with releasing the next version 👍🏻 with this PR:
https://github.com/abdolence/gcloud-sdk-rs/pull/147

**Comment by abdolence** [comment]
@zackangelo Seems in the version of Reqwest, this `Sync` is now required, so I have to revert this in 0.25.

**Comment by abdolence** [comment]
![image](https://github.com/user-attachments/assets/12dd9d45-03e2-4991-8386-8981cecf41c5)

**Comment by abdolence** [comment]
They have removed it again in the last commits:
https://github.com/seanmonstar/reqwest/pull/2361

As soon as they release it I'll relax it again.
