### ISSUE TITLE
Feature tls-webpki-roots causes duplicate definition

### ISSUE THREAD

**Issue by waywardcoder** [abdolence/gcloud-sdk-rs#160]
I was building off the example for gcp secrets and when enabling feature tls-webpki-roots like the example i get an error that duplicate definitions exist:

error[E0592]: duplicate definitions with name `init_tls_config`
   --> /Users/chrisdupuy-admin/.cargo/git/checkouts/gcloud-sdk-rs-492432f787671ff2/4f4ba97/gcloud-sdk/src/api_client.rs:231:5
    |
224 |     fn init_tls_config(domain_name: String) -> tonic::transport::ClientTlsConfig {
    |     ---------------------------------------------------------------------------- other definition for `init_tls_config`
...
231 |     fn init_tls_config(domain_name: String) -> tonic::transport::ClientTlsConfig {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ duplicate definitions for `init_tls_config`

when looking at the code it does appear both are included unless you use tls-roots:

![image](https://github.com/user-attachments/assets/20b4ef42-e40d-4541-920f-ef121b538218)

**Comment by abdolence** [comment]
To be able to use another TLS config you need to disable default-features since it has conflicting feature.

**Comment by waywardcoder** [comment]
Thank you!  Sorry i missed that in the cargo.toml

**Comment by abdolence** [comment]
No worries, I know the addictive nature of Cargo features might be quite frustrating, especially through transitive dependencies.
