### ISSUE TITLE
Cloud Storage Bug: Incorrect base url for uploading objects into buckets

### ISSUE THREAD

**Issue by decaffjoe** [abdolence/gcloud-sdk-rs#22]
# The issue

For uploading objects to storage buckets the base url provided by `create_google_storage_v1_config()` is incorrect. It incorrectly provides the path `/storage/v1`, but the correct path is `/upload/storage/v1`

This code snippet works (assuming you defined `params`):

```rs
    let google_rest_client = gcloud_sdk::GoogleRestApi::new().await?;
    let mut config = google_rest_client.create_google_storage_v1_config().await?;
    
    // have to change base path to include /upload/
    config.base_path = "https://storage.googleapis.com/upload/storage/v1".to_string();

    let response = gcloud_sdk::google_rest_apis::storage_v1::objects_api::storage_objects_insert(
        &config, params,
    )
    .await?;
```

## Unrelated question

Where do you attach the actual _data_ for inserting data into a bucket? I don't see an option on `Object` or `StoragePeriodObjectsPeriodInsertParams`

```rs
    let mut object = gcloud_sdk::google_rest_apis::storage_v1::Object::default();
    object.bucket = Some("bucket_name".to_string());
    object.name = Some("object_name".to_string());
    // object.data = object_data;  // this property doesn't exist, where does the data go?

    let mut params = gcloud_sdk::google_rest_apis::storage_v1::objects_api::StoragePeriodObjectsPeriodInsertParams::default();
    params.bucket = "bucket_name".to_string();
    params.name = Some("object_name".to_string());
    params.object = Some(object);
    // params.data = object_data;  // likewise, this property doesn't exist either
```

Maybe I'm missing it somewhere, it's late

**Comment by abdolence** [comment]
Hey, 
The upload object has another API which I guess is not described formally as OpenAPI anywhere (I didn't find at least it).

The good news is that I've written a custom extension particularly for the upload case. Have a look at:
`google_storage_v1_upload_stream_bytes` in `gcloud_sdk::GoogleRestApi`.

```
let uploaded_object: gcloud_sdk::google_rest_apis::storage_v1::object::Object =  google_rest_client
            .google_storage_v1_upload_stream_bytes(
                bucket_name,
                filename,
                content_type,
                bytes_stream,
            )
            .await?
```

**Comment by abdolence** [comment]
This method doesn't support for now some extension parameters such as ACLs, so PRs are welcome if you need any.

**Comment by abdolence** [comment]
I'll give try to make some kind of extension to the OpenAPI generator for this case to support it somehow better.

**Comment by decaffjoe** [comment]
Ok that's great, right on thank you!!

**Comment by abdolence** [comment]
God, I hate bash-programming, but it was the easiest way to inject some extensions and seems I managed to do it:

I left you an example in GCS:

```rust
// Upload to GCS has a slightly different API that OpenAPI doesn't support, so there is an extension method in this library to support this
async fn test_upload(bucket: &str, filename: &str, google_rest_client: &GoogleRestApi) -> Result<(), Box<dyn std::error::Error>> {

    let response = gcloud_sdk::google_rest_apis::storage_v1::objects_api::storage_objects_insert_ext_bytes(
        &google_rest_client.create_google_storage_v1_config().await?,
        gcloud_sdk::google_rest_apis::storage_v1::objects_api::StoragePeriodObjectsPeriodInsertParams {
            bucket: bucket.to_string(),
            name: Some(filename.to_string()),
            ..Default::default()
        },
        None,
        "Hello".as_bytes().to_vec()
    ).await?;

    println!("{:?}", response);

    Ok(())
}
```
There is also stream version `_stream` which is useful if you have stream incoming outside (files/network/etc)

**Comment by abdolence** [comment]
Available in 0.19.4.
Didn't have time to test it thoroughly - let me know if it doesn't work for you

**Comment by abdolence** [comment]
Close this for now, if the problem still exists feel free to reopen it.

**Comment by decaffjoe** [comment]
Hey sorry forgot to respond- the new method works great now. Also thanks for making the data argument just be a `Vec<u8>` instead of a pinned box etc...
