### ISSUE TITLE
Cloud we have a bigquery storage write api example on this crate?

### ISSUE THREAD

**Issue by WENPIN1** [abdolence/gcloud-sdk-rs#59]
Hi 
Cloud we have a bigquery storage write api example on this crate?
There are many uwanted problems when using this crate for bigquery storage write API via grpc. 
    let response1 = bigquery_storage_client
        .get()
        .append_rows(append_request)
        .await
        .unwrap();
        
If we have an example, it will have a great help!

Thank you all !
-WENPIN

**Comment by abdolence** [comment]
Hey,

BigQuery APIs are complex and cumbersome on the low level, but still doable.
I left an example for you here:
https://github.com/abdolence/gcloud-sdk-rs/tree/master/examples/bigquery-storage-write-client

**Comment by WENPIN1** [comment]
Hi Abdulla,
Thank you for your handsome very much!

-WENPIN1
