### ISSUE TITLE
Is it possible to fetch Id token using this crate?

### ISSUE THREAD

**Issue by i10416** [abdolence/gcloud-sdk-rs#78]
Java, go, node and Python can fetch id token from GoogleCredentials.
Is it possible to support this feature in gcloud-sdk-rs?

There are some reference implementations available
- Java: https://github.com/googleapis/google-auth-library-java/blob/b152e76386c54e5682969f4ba5157f4bc20e7fb5/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java#L566
- golang: https://github.com/googleapis/google-api-go-client/tree/main/idtoken
- node: https://github.com/googleapis/google-auth-library-nodejs/tree/3563c16e2376729e399fefc0b1fad7bff78c296e/src/auth

https://cloud.google.com/docs/authentication/get-id-token

**Comment by abdolence** [comment]
Hey, as your links also mentioned, there are different options to get ID token.

The first (which is already available in the released version of this library) is using [Generate an ID token by impersonating a service account](https://cloud.google.com/docs/authentication/get-id-token#impersonation):

```
    let client: GoogleApi<IamCredentialsClient<GoogleAuthMiddleware>> = GoogleApi::from_function(
        IamCredentialsClient::new,
        "https://iamcredentials.googleapis.com",
        // cloud resource prefix: used only for some of the APIs (such as Firestore)
        None,
    )
    .await?;

    // Option 1: using service account impersonation
    let resp = client
        .get()
        .generate_id_token(tonic::Request::new(GenerateIdTokenRequest {
            name: format!(
                "projects/-/serviceAccounts/{}",
                std::env::var("SERVICE_ACCOUNT")?
            ),
            audience: "test-aud".to_string(),
            ..Default::default()
        }))
        .await?;
```

The second option is to use Metadata server but it will work only on GCP. 
Unfortunately, this option wasn't available before my latest changes in master (https://github.com/abdolence/gcloud-sdk-rs/pull/82), but you can try it with the master branch.

Hope this helps

**Comment by abdolence** [comment]
The second option is now available starting with https://github.com/abdolence/gcloud-sdk-rs/releases/tag/v0.20.3

Feel free to reopen this if you see something missing or issues.
