### ISSUE TITLE
Clarification regarding identitytoolkit v1

### ISSUE THREAD

**Issue by brprkr** [abdolence/gcloud-sdk-rs#84]
I was recently working with KMS, and really appreciated the thought that has gone into this crate. Many thanks!

I'm interested in using some of the Firebase/IdentityPlatform authentication features, in the same way one would use the Firebase Auth ([Admin](https://firebase.google.com/docs/firestore/client/libraries#firebase_admin_sdks)) SDKs in Python, Go, etc. My concerns include server-side user creation, email verification links, OOB codes, [session cookies](https://firebase.google.com/docs/auth/admin/manage-cookies#go), and identity-platform [multi-tenant usage](https://firebase.google.com/docs/reference/admin/python/firebase_admin.tenant_mgt). 

Looking at the [REST reference for Firebase Auth](https://firebase.google.com/docs/reference/rest/auth), it seems most of it relies on V1 of the `identitytoolkit` API. I haven't found any documentation on why most of those [endpoints](https://cloud.google.com/identity-platform/docs/reference/rest) aren't carried over to V2, but they still seem to be in use.

(Note: everything is confused further by Google's exhortations to ["migrate from Google Identity Toolkit to Google Cloud's Identity Platform"](https://developers.google.com/identity/toolkit/migrate-identityplatform), without much clarification on naming.) 

Would codegen for V1 of `identitytoolkit` be considered out of scope for this crate, or were there any particular reasons or insights into that version's status that went into its exclusion? If you're willing I'd also appreciate any suggestions you might have on accessing these endpoints/capabilities otherwise from Rust -- right now I'm weighing manually calling the REST API or making a separate service with one of the other language SDKs, and feel I may be missing something in the ecosystem.

Thank you again!

**Comment by brprkr** [comment]
I see that V1 isn't included in the googleapis [openapi-directory](https://github.com/APIs-guru/openapi-directory/tree/main/APIs/googleapis.com/identitytoolkit) or the [protos](https://github.com/googleapis/googleapis) repository this crate uses, so closing this out. Thanks!

**Comment by abdolence** [comment]
Hey, I agree that this whole thing around identity platform and IAM is confusing from Google.
`identitytoolkit v1` is in the scope, the only problem I see that I wasn't able to find it in my sources:

https://github.com/googleapis/googleapis/tree/master/google/cloud/identitytoolkit
https://github.com/APIs-guru/openapi-directory/tree/main/APIs/googleapis.com/identitytoolkit

Do you know any source for at least OpenAPI spec?

**Comment by abdolence** [comment]
Even if it is not included, if you have a good spec we can include it. I just need the spec :)

**Comment by abdolence** [comment]
Ok, found it on the official google portal using their discovery service.
https://identitytoolkit.googleapis.com/$discovery/rest?version=v1

Let me do some research if it can be included easily.

**Comment by brprkr** [comment]
Thanks for the quick reply!! I'll try to poke around too for examples of how this has been approached elsewhere.

**Comment by brprkr** [comment]
I'm still experimenting and not sure where this will go, but a quick update on my end. I've made a [fork](https://github.com/brprkr/google-discovery-to-openapi.git) of [stackql/google-discovery-to-openapi](https://github.com/stackql/google-discovery-to-openapi), and patched it to process non-preferred versions. (I'll wait to see how our efforts play out before upstreaming -- I haven't spent too much time in the repository and may have broken some things).

The command on my system to generate with the non-preferred option is `node bin/google-discovery-to-openapi.mjs generate -n`.

(Note you'll get a lot of error's relating to not finding things in `lostandfound`. This was the case for me before my patch. Luckily identitytoolkit isn't one of them).

I've also included a temporary branch with the `openapi` output unignored. The resulting `identitytoolkit-v1.yaml` can be found [here](https://github.com/brprkr/google-discovery-to-openapi/blob/temp-include-outputs/openapi/cloud/identitytoolkit/identitytoolkit-v1.yaml).

Note that it's `openapi: 3.1.0`, whereas the specs used by this crate are I think 3.0.0.

Kind of ad hoc, and I haven't gotten to trialing it with gcloud-sdk-rs. (I don't have Java installed for OpenAPI Generator -- so will take some time on my end.)

**Comment by abdolence** [comment]
I actually tried that tool today, and it had some issues with schema and undefined references. I didn't have time to dig more, but it seems it may not generate everything accurately, but let me know if you get some better results than me. I read that people use that tool and fix spec themselves manually which I find annoying for long term :)

**Comment by brprkr** [comment]
Yes, encountered probably the same errors. I'm not volunteering to maintain a manually patched version, and wouldn't ask anyone else to :) 

Do you mind if I reopen with a new title, in case anyone else has ideas? I'll also try to open an issue with APIs-guru this week unless you're opposed.

Thanks for you help!
