### ISSUE TITLE
Question: What do you think about re-exporting tonic crate?

### ISSUE THREAD

**Issue by i10416** [abdolence/gcloud-sdk-rs#99]
We often encounter compile error from gcloud_sdk_rs crate when we upgrade tonic because gcloud_sdk_rs exposes tonic types(e.g. tonic::Request) in public interfaces. What do you think about re-exporting tonic?

**Comment by abdolence** [comment]
Makes sense, implemented in https://github.com/abdolence/gcloud-sdk-rs/releases/tag/v0.21.0
